### ISSUE TITLE
Maybe you can change your "circle" into a crazy virus by adjusting the form

### ISSUE THREAD

**Issue by jenniferslagt** [Ramon96/real-time-web-1920#6]
check this: https://thenounproject.com/search/?q=virus ![bitmoji](https://render.bitstrips.com/v2/cpanel/3c97455d-0ce1-4ac8-82a0-601e6d6f6fd2-83c93cc0-d0ae-4742-a59b-b1a0ec5de8e6-v1.png?transparent=1&palette=1&width=246)

**Comment by Ramon96** [comment]
Awesome Idea, will add this after the grading.
